- .gitignore
- backend/api/managed/router.py
- backend/requirements.txt
- backend/utils/pdf.py
- initialize pdf
- add missing packages
- update git igmore
> [POS-1837] Move creating PDF feature to the new dmart

- backend/config/notification.json
- backend/models/core.py
- backend/plugins/firebase_notifier.py
- backend/plugins/sms_notifier.py
- backend/plugins/web_notifier.py
- backend/utils/helpers.py
- backend/utils/notification.py
- backend/utils/repository.py
- backend/utils/settings.py
**Idea**
- Notifications are essential part of Dmart
- Supported type/s (platform/s) of the notifications are dynamic and customizable
**Implementation**
- A new `Notifier` class acts as a base class or contract for any notifier type class (SMS, firebase, web)
- `WebNotifer`, `SMSNotifier`, and `FirebaseNotifier` classes were added as files in `backend/plugins` folder and can be activated/deactivated using the new config file located at `backend/config/notification.json`
- A new `NotificationManager` class responsible for
- loading plugins dynamically based on the config file
- forward the send action to the appropriate Notifier
> Refactoring notifications

- backend/utils/redis_services.py
> Revert "cont."

- backend/api/user/router.py
- backend/utils/custom_validations.py
- backend/utils/redis_services.py
> Revert " email unique validation"

- frontend/src/components/management/Aggregation.svelte
- frontend/src/components/management/QueryFormH.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/SchemaEntryRenderer.svelte
- frontend/src/components/management/renderers/TicketEntryRenderer.svelte
- frontend/src/components/management/renderers/UserEntryRenderer.svelte
- frontend/src/components/management/renderers/WorkflowRenderer.svelte
- frontend/src/dmart/index.ts
- frontend/src/routes/management/content/[space_name]/[subpath]/[shortname]/[resource_type]/json/api.svelte
- frontend/src/routes/management/tools/info.svelte
- frontend/src/stores/management/sections.json
1. Remove activate/deactivate button
3. Under tools add : Server info section to show the results of /info/manifest and /info/settings, and link to docs
4. Support aggregation in the query section:
> Adding features

- frontend/src/components/management/renderers/EntryRenderer.svelte
When resource type "ticket" is selected, content type should strictly be json.  (I'm thinking also about schema short name in that case)
> #232 Ticket creation restriction

- frontend/src/components/Login.svelte
- frontend/src/components/management/Aggregation.svelte
- frontend/src/components/management/Attachments.svelte
- frontend/src/components/management/Media.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/dmart/index.ts
- Remove meta_schema and folder_renderer from the list of schema options and only show the remaining available schemas if any.
- "ticket" resource type should only be shown if workflows folder exist in the space and contains one workflow.
- Add warning in case of failed login.
> #232 Enhancements

- frontend/src/components/management/Attachments.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/WorkflowRenderer.svelte
- fix the issue for the missing states for the workflows.
- add the editor option for adding schema entry.
- add the missing default is_active.
- adding the ability to edit attachments.
> Enhancements

- frontend/src/components/management/renderers/EntryRenderer.svelte
- Prefill content for permission and role when creating entry
- Fix the miss leading label above json editor when creating permission/role
> Enhance EntryRenderer.svelte

- frontend/src/App.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/UserEntryRenderer.svelte
- frontend/src/dmart/index.ts
- using user/create to create users.
- performing a shortname/email/msisdn/password check before sending a user create/update request.
- set the right lang for space upon lang switching
> Fix UI errors

- backend/api/managed/router.py
- backend/models/enums.py
- frontend/src/components/management/Attachments.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/WorkflowRenderer.svelte
- frontend/src/dmart/index.ts
- adding csv and jsonl to the attachments (backend/frontend).
- keeping only json,text,md,html when creating content. 
- add content preview for json,text,md,html.
> Extending UI

- frontend/src/components/management/Attachments.svelte
- frontend/src/components/management/ListView.svelte
- frontend/src/components/management/Media.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/dmart/index.ts
- frontend/src/routes/management/content/[space_name]/index.svelte
- frontend/src/utils/columnsUtils.ts
- consuming parent folder rendering to render the cols, if does not exist fallback to default one.
- fix updating 1st level folder
> honoring folder rendering

- frontend/src/components/management/editors/JsonSchemaChild.svelte
- frontend/src/components/management/editors/SchemaEditor.svelte
- frontend/src/components/management/editors/SchemaEditor2.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/SchemaEntryRenderer.svelte
- frontend/src/components/management/renderers/SpaceRenderer.svelte
- frontend/src/components/management/renderers/TicketEntryRenderer.svelte
- frontend/src/components/management/renderers/UserEntryRenderer.svelte
- frontend/src/components/management/renderers/WorkflowRenderer.svelte
- frontend/src/utils/editors/schemaEditorUtils.ts
- frontend/src/utils/renderer/rendererUtils.ts
- frontend/src/utils/renderer/schemaEntryRenderer.ts
- frontend/src/utils/renderer/workflowRendererUtils.ts
- Code refractoring
- Fixing both JsonForm/SchemaForm Editor for create/update entries (UPDATE by using SchemaForm Editor is ONLY for Entry of type content so far)
- Adding more validation options:
```
"integer": [
"minimum"
"maximum"
]
"string": [
"minLength
"maxLength
"enum"
"pattern"
]
"array": [
"minItems"
"maxItems"
"uniqueItems"
]
"is_required"
```
- Pending:
```
let validationFormats = [
"date",
"time",
"date-time",
"duration",
"regex",
"email",
"idn-email",
"hostname",
"idn-hostname",
"ipv4",
"ipv6",
"json-pointer",
"relative-json-pointer",
"uri",
"uri-reference",
"uri-template",
"iri",
"iri-reference",
"uuid"
];
```
> Various Improvements

- frontend/src/components/management/editors/JsonSchemaChild.svelte
- frontend/src/components/management/editors/SchemaEditor.svelte
- frontend/src/utils/editors/schemaEditorUtils.ts
SchemaEditor:
- Add steps for Number (to allow floats).
- Remove unused props.
- Set type of array based on content.
> Fix SchemaEditor

- frontend/src/components/management/editors/JsonSchemaChild.svelte
- frontend/src/components/management/editors/SchemaEditor.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/utils/editors/schemaEditorUtils.ts
- frontend/src/utils/renderer/rendererUtils.ts
- Make key required for Schema form editor.
- Bind the FormEditor and JSONEditor (one way form->json).
- disable root changes for key and type.
- Update the UI schema form.
> Various improvments

- frontend/src/components/management/ListView.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/Forms/UserForm.svelte
- frontend/src/routes/_module.svelte
- frontend/src/stores/management/bulk_bucket.ts
- Using dropdown for workflows
- Adding User form
- Adding bulk feature
> Adding various features

- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/Forms/UserForm.svelte
- frontend/src/utils/renderer/rendererUtils.ts
- fix MSISDN issues
- fix payload not being set
- fix roles not being set
- fix create permission issue
> Fixing various issues

- frontend/index.html
- frontend/package.json
- frontend/src/App.svelte
- frontend/src/app.css
- frontend/src/components/management/Header.svelte
- frontend/src/components/management/ListView.svelte
- frontend/src/components/management/Sidebar.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/SpaceRenderer.svelte
- frontend/src/components/management/sidebar/Profile.svelte
- frontend/src/components/management/sidebar/SimpleSpaces.svelte
- frontend/src/components/management/sidebar/Spaces.svelte
- frontend/src/routes/management/content/[space_name]/[subpath]/[shortname]/[resource_type]/[payload_type]/api.svelte
- frontend/src/routes/management/content/[space_name]/[subpath]/[shortname]/[resource_type]/json/api.svelte
- frontend/vite.config.ts
- Evolve our routify / multi-lang solution to cover folder / index files
- Improve lighthouse scores ... e.g. improve vite chunking : regular public page or sysadmin
- Bulk ... add select all
> Various improvements 

- backend/requirements.txt
> redis >= 5.0.3

- readme.md
> fix images

- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/Forms/RelationshipForm.svelte
- frontend/src/components/management/renderers/UserEntryRenderer.svelte
- frontend/src/dmart/index.ts
Checking the added relationship before proceeding to submission.
> Improving RelationshipForm

- readme.md
**Updated readme.md file offline deployment section to** 
1. clean up any prior venv setup 
2. run virtualenv on python 3.11
> Updated readme.md file offline deployment section

- backend/loadtest/locustfiles/managed_test.py
Improved File Path Handling for "login_creds.sh"
> refactor:Fix Login_Creds file Path not found

- backend/data_adapters/sql_adapter.py
- search in JSON list against string
- fix bug when we have multi-criteria
> Enhance search

- .gitignore
- backend/.coveragerc
- backend/pylint.sh
- backend/pyrightconfig.json
- backend/pytests/api_user_models_erros_test.py
- backend/pytests/api_user_models_requests_test.py
- backend/pytests/archive_test.py
- backend/pytests/data_adapters_test/adapter_test.py
- backend/pytests/data_adapters_test/sql_adapter_test.py
- backend/pytests/get_settings_test.py
- backend/pytests/json_to_db_migration_test.py
- backend/pytests/models_test/api_test.py
- backend/pytests/models_test/enums_test.py
- backend/pytests/service_test.py
- backend/pytests/test_info.py
- backend/requirements.txt
- **adding .venv to the ignore Foldes**
- **adding .coverage ignore**
- **test user models error scheme**
- **test user models requests**
- **adding pytest-cov**
- **Increased the Test to 65%**
> unit test part one

- .github/workflows/docker-build-push.yml
This PR introduces a GitHub Actions workflow to automate the process of building and pushing Docker images to the GitHub Container Registry (GHCR) whenever:
1. A new tag is pushed to the `master` branch.
2. A new release is published.
The workflow is designed to be customizable and includes detailed comments for clarity.
---
1. **New Workflow File**:
- Added `.github/workflows/docker-build-push.yml` to define the Docker build and push process.
2. **Workflow Features**:
- Triggers on:
- Tag pushes matching the pattern `v*` to the `master` branch.
- Published releases.
- Builds a Docker image using the `admin_scripts/docker/Dockerfile`.
- Tags the image with:
- The Git tag (e.g., `v1.0.0`).
- The `latest` tag if the release is stable (not a pre-release).
- Pushes the image to the GitHub …
> Add GitHub Actions Workflow for Docker Build and Push

- backend/api/managed/router.py
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/TicketEntryRenderer.svelte
- frontend/src/routes/management/_module.svelte
- fixing TicketEntryRenderer
- fix svg rendering
- fix ConfigEditor TranslationEditor
> Fixing Ticket render and SVG issue

- backend/data_adapters/sql/adapter_helpers.py
example:
```
@created_at:[2022-08-23 2022-08-29]
```
to handle:
```
[2022-08-23 2022-08-23]
[2022-08-23T:00:00:00 2022-08-23T23:59:59]
[2022-08-23T:00:00:00.000000 2022-08-23T23:59:59.999999]
```
> Add search by date range

- backend/api/managed/router.py
- backend/api/managed/utils.py
- backend/api/user/router.py
- cli/cli.py
- frontend/package.json
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/routes/management/content/[space_name]/[subpath]/[shortname]/[resource_type]/[payload_type]/api.svelte
- frontend/src/routes/management/content/[space_name]/[subpath]/[shortname]/[resource_type]/json/api.svelte
- frontend/src/utils/checkAccess.ts
- [frontend] removing deprecated checkAccess
- [frontend] adding displayname/description/tags field
- [backend] making schema_shortname optional and parse list values
- [backend] fixing login by identifier (email, msisdn)
- [cli] making resource_type@mandatory and schema_shortname@optional
> Multi-improvement  

- backend/data_adapters/sql/adapter.py
- frontend/package.json
- frontend/src/components/management/HistoryListView.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/UserEntryRenderer.svelte
- [backend] Fixing pagination issue
- [backend] limit can't be 0
- [frontend] Fixing rendering issues
> Fix various issues

- backend/data_adapters/sql/adapter.py
- frontend/src/components/management/Attachments.svelte
- frontend/src/components/management/HistoryListView.svelte
- frontend/src/components/management/ListView.svelte
- frontend/src/components/management/renderers/EntryRenderer.svelte
- frontend/src/components/management/renderers/UserEntryRenderer.svelte
- [frontend] fix save payload
- [frontend] rename some of var/method names
- [frontend] fix rendering issues
- [backend] fix deletion order for space
- [backend] impl allowed_fields_values for sql mode
> Fixing bugs

- backend/data_adapters/sql/adapter.py
- backend/data_adapters/sql/adapter_helpers.py
@payload.body.$array.key:value
> search in payload array

- cli/cli.py
- frontend/src/components/management/renderers/EntryRenderer.svelte
- [frontend] disabling relationship (WIP)
- [backend] fixing CLI: single arg for request command
> Disabling relationship and fixing CLI

- backend/api/public/router.py
```
PYTHON: pydmart-1.0.9
DART:   dmart 1.1.2 
NPM:    @edraj/tsdmart@2.1.1
```
> add resource_with_payload for public

- backend/api/public/router.py
- backend/models/enums.py
- backend/utils/ticket_sys_utils.py
drivers:
- [dart](https://pub.dev/packages/dmart): 1.3.0
- [pydmart](https://pypi.org/project/pydmart/1.1.0/): 1.1.0
- [tsdmart](https://www.npmjs.com/package/@edraj/tsdmart):  2.3.0
> extend public/submit to have ticket

- backend/api/public/router.py
fixing an issue , where initial state roles in a ticket workflow is not properly checking with the user (anonymous) role when submitting a ticket  , using public/submit endpoint
> check ticket initial state for public submissions

- backend/pytests/feature/test_query_extensive.py
added a file to extensively test querying for different search scenarios  such as meta.array , meta.string , meta.boolean ,meta.int ,payload.string ,payload.string , payload.array , payload.boolean Etc.
> qurey tests

- backend/api/managed/router.py
- backend/api/managed/utils.py
- backend/data_adapters/sql/adapter.py
- backend/data_adapters/sql/json_to_db_migration.py
- cli/cli.py
- fix logging
- upload csv enhancement
> Multi enhancements
